<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>LibRincewindPlugin_ChaCha20_4.7.2</AssemblyName>
    <RootNamespace>LibRincewindPlugin_ChaCha20_4._7._2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Blowfish.cs" />
    <Compile Include="ChaChar20.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibRincewindPlugin_4.7.2\LibRincewindPlugin_4.7.2.csproj" />
  </ItemGroup>

</Project>
