<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>LibRincewindRNG_Generic_API</AssemblyName>
    <RootNamespace>LibRincewindRNG_Generic_API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Rng.cs" />
    <Compile Include="..\LibRincewindRNG_Shared\EntropyConditioner.cs">
      <Link>EntropyConditioner.cs</Link>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibRincewindPlugin_4.7.2\LibRincewindPlugin_4.7.2.csproj" />
  </ItemGroup>

</Project>
