/*
Copyright 2023 Dennis Michael Heine

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;

namespace LibRincewind_4._7._2
{
    /// <summary>
    /// LibRincewind core cipher.
    ///
    /// GOAL
    /// ----
    /// Hide the key space of the ciphertext: an offline attacker who tries every
    /// candidate password must get a plausible-looking plaintext for *every* one of
    /// them, so that the ciphertext alone gives no way to recognise the right key.
    ///
    /// HOW IT IS ACHIEVED
    /// ------------------
    /// The cipher is a format-preserving stream cipher over the 95 printable ASCII
    /// characters (0x20..0x7E). Plaintext space and ciphertext space are the same
    /// set, and encryption is a bijection on it:
    ///
    ///     c[i] = (p[i] + ks[i]) mod 95
    ///     p[i] = (c[i] - ks[i]) mod 95
    ///
    /// where ks is a uniform pseudorandom digit stream in [0,95) derived from the
    /// passwords. Because the envelope stores no key material, no checksum, no MAC
    /// and no padding, decrypting with a wrong password yields a string that is
    /// uniformly distributed over all printable strings of the same length. There is
    /// nothing in the output an attacker can test against, so brute force gives no
    /// signal at all. That is the property this library is supposed to have; the
    /// previous rotation-based construction did not have it (see NOTES).
    ///
    /// TRADE-OFF YOU ARE ACCEPTING
    /// ---------------------------
    /// This property is incompatible with integrity protection. A MAC is exactly the
    /// oracle we are removing, so LibRincewind is deliberately unauthenticated:
    /// ciphertext is malleable and a corrupted ciphertext decrypts silently to
    /// garbage. Use it where deniability matters more than tamper detection. If you
    /// need tamper detection, wrap the envelope in a separate HMAC — and understand
    /// that doing so gives the brute forcer the key check back.
    ///
    /// Second trade-off: the plaintext must consist of printable ASCII only. Any
    /// escaping or length header for other input would be redundancy, and redundancy
    /// is a key check. Non-conforming input is rejected loudly rather than silently
    /// weakening the guarantee.
    ///
    /// NOTES ON WHAT WAS WRONG BEFORE
    /// ------------------------------
    ///  * Encryption rotated each byte an unrecorded number of times "until it looked
    ///    printable"; decryption guessed that count and gave up after 2 tries, writing
    ///    the literal byte 254. The round-trip was mathematically ambiguous, so it
    ///    could not work and did not work.
    ///  * The rotation was a 7-bit rotate, which preserves the Hamming weight of every
    ///    byte and confines each plaintext byte to an orbit of at most 7 values. That
    ///    leaks the plaintext almost completely and is the opposite of hiding the key
    ///    space.
    ///  * The payload was never handed to the cipher plugin at all (the call was
    ///    commented out); only the throwaway key was encrypted.
    ///  * The RNG fallback was System.Random, seeded from the clock, with a
    ///    Thread.Sleep(10..200 ms) per generated byte to stop it repeating itself.
    ///    That is both insecure and roughly 100 000x slower than a CSPRNG.
    ///  * The IV was generated once per instance and reused for every message, which
    ///    is fatal for the stream-cipher plugins.
    ///  * BinaryFormatter was used for the envelope (remote code execution on
    ///    deserialise, and removed outright from modern .NET).
    /// </summary>
    public class CRincewind
    {
        // ---------------------------------------------------------------- domain --

        /// <summary>First character of the working alphabet (space).</summary>
        public const byte AlphabetMin = 32;

        /// <summary>Last character of the working alphabet (tilde).</summary>
        public const byte AlphabetMax = 126;

        /// <summary>Size of the working alphabet: 95 printable ASCII characters.</summary>
        public const int AlphabetSize = AlphabetMax - AlphabetMin + 1;

        /// <summary>
        /// Largest multiple of <see cref="AlphabetSize"/> that fits in a byte. Random
        /// bytes at or above this are discarded so the digit stream stays exactly
        /// uniform; taking b % 95 over the full byte range would bias the low digits.
        /// </summary>
        private const int RejectionBound = (256 / AlphabetSize) * AlphabetSize; // 190

        // -------------------------------------------------------------- envelope --

        private const string EnvelopeTag = "RW6";
        private const char EnvelopeSeparator = '.';   // not part of the Base64 alphabet
        private const int SaltSize = 32;
        private const int DefaultIvSize = 16;

        // ------------------------------------------------------------ Argon2id cost --
        //
        // Argon2id rather than PBKDF2 because PBKDF2-SHA256 is cheap to parallelise on
        // GPUs and ASICs: it needs almost no memory, so an attacker buys throughput
        // linearly with silicon. Argon2id forces every guess through MemoryKiB of RAM,
        // which is the one resource a cracking rig cannot multiply cheaply. Since the
        // ciphertext offers no way to recognise a correct key, the KDF cost is what an
        // attacker pays per candidate, and it is worth making that cost memory-bound.
        //
        // Defaults follow the OWASP recommendation of 64 MiB / t=3 / p=4. They are the
        // cost per operation, so measure before raising them on a machine that decrypts
        // many records at once.

        /// <summary>Argon2id memory cost in KiB. Default 65536 (64 MiB).</summary>
        public static int Argon2MemoryKiB = 65536;

        /// <summary>Argon2id time cost (passes over memory). Default 3.</summary>
        public static int Argon2Iterations = 3;

        /// <summary>Argon2id lanes. Default 4.</summary>
        public static int Argon2Parallelism = 4;

        /// <summary>
        /// Largest memory cost this build will honour when reading a record, default
        /// 1 GiB. Records carry their own cost parameters so they stay readable after the
        /// defaults change — which means a hostile record could otherwise ask for 64 GiB
        /// and take the process down. Anything above this ceiling is rejected as a
        /// malformed record rather than allocated.
        /// </summary>
        public static int Argon2MaxMemoryKiB = 1048576;

        /// <summary>
        /// How many master keys to keep in memory so that repeated operations under the
        /// same password and salt pair do not repay the KDF cost. 0 (the default) disables
        /// caching, so every call is a full Argon2id pass.
        ///
        /// OFF BY DEFAULT ON PURPOSE. A cache hit returns in microseconds while a miss
        /// takes the best part of a second, so an attacker who can time operations against
        /// a *running, already-unlocked* process can tell "password seen before" from
        /// "password not seen before". That is not a break of the offline guarantee — a
        /// brute forcer working from a stolen ciphertext misses on every candidate,
        /// including the right one — but it is a live-process side channel, and this
        /// library's whole selling point is that there is no way to recognise the right
        /// key. Turn it on only when you have decided that trade is worth it:
        ///
        ///     CRincewind.MasterKeyCacheSize = 8;   // e.g. an unlocked vault UI
        ///
        /// Enabling it is worth roughly a 50000x speed-up per record for a vault that
        /// keeps one salt pair across all its entries. The cache holds derived keys, not
        /// passwords, and its lookup keys are HMACs under a random process-local key, so
        /// the table itself reveals nothing about the passwords. It is still secret
        /// material resident in memory: call <see cref="ClearKeyCache"/> when locking.
        /// </summary>
        public static int MasterKeyCacheSize = 0;

        // ---------------------------------------------------------------- state ---

        private readonly IPlugin plugin;
        private readonly int ivSize;

        /// <summary>
        /// IV of the most recent operation. Every message gets a fresh one; this field
        /// exists so callers can inspect it and is not an input to encryption.
        /// </summary>
        public byte[] IV;

        /// <summary>Optional external entropy source. Null selects the OS CSPRNG.</summary>
        public static IRng Rng = null;

        /// <summary>
        /// Per-character keystream digits of the last encrypt / decrypt, exposed for
        /// the demo's diagnostics. Kept for API compatibility; these are static and
        /// therefore not safe to read from another thread while a call is in flight.
        /// </summary>
        public static int[] rotations = new int[1];
        public static int[] rotationsDec = new int[1];

        // ---------------------------------------------------------------- setup ---

        /// <param name="_plugin">Path to an IPlugin DLL, or "" for the built-in AES-CTR keystream.</param>
        /// <param name="_rng">Path to an IRng DLL, or "" for the OS CSPRNG.</param>
        /// <param name="ivSize">
        /// IV length in bytes. Must match what the chosen plugin expects
        /// (ChaCha20: 12, RC4Plus: 16). Minimum 8.
        /// </param>
        public CRincewind(string _plugin, string _rng, int ivSize = DefaultIvSize)
        {
            if (ivSize < 8)
                throw new ArgumentOutOfRangeException("ivSize", "IV must be at least 8 bytes.");

            this.ivSize = ivSize;
            this.plugin = LoadPlugin(_plugin);
            Rng = LoadRng(_rng);
            this.IV = QRNG(ivSize);
        }

        private static IPlugin LoadPlugin(string path)
        {
            if (string.IsNullOrEmpty(path))
                return null;

            foreach (Type t in Assembly.LoadFile(path).GetExportedTypes())
            {
                if (t.GetInterfaces().Contains(typeof(IPlugin)) && !t.IsAbstract)
                    return (IPlugin)Activator.CreateInstance(t);
            }
            throw new ArgumentException("No IPlugin implementation found in " + path, "path");
        }

        private static IRng LoadRng(string path)
        {
            if (string.IsNullOrEmpty(path))
                return null;

            foreach (Type t in Assembly.LoadFile(path).GetExportedTypes())
            {
                if (t.GetInterfaces().Contains(typeof(IRng)) && !t.IsAbstract)
                    return (IRng)Activator.CreateInstance(t);
            }
            throw new ArgumentException("No IRng implementation found in " + path, "path");
        }

        // ------------------------------------------------------------ public API --

        /// <summary>True if every character of <paramref name="s"/> is in the working alphabet.</summary>
        public static bool IsSupported(string s)
        {
            if (s == null) return false;
            for (int i = 0; i < s.Length; i++)
                if (s[i] < AlphabetMin || s[i] > AlphabetMax) return false;
            return true;
        }

        /// <summary>
        /// Encrypts <paramref name="toEncrypt"/> into a ciphertext drawn from the same
        /// printable-ASCII alphabet and of the same length.
        /// </summary>
        /// <param name="salt1">Caller-supplied salt, or null to generate a fresh one.</param>
        /// <param name="salt2">Caller-supplied salt, or null to generate a fresh one.</param>
        public CCryptData encryptCCD(string toEncrypt, string password1, string password2,
                                     byte[] salt1, byte[] salt2)
        {
            if (toEncrypt == null) throw new ArgumentNullException("toEncrypt");
            RequireAlphabet(toEncrypt);

            if (salt1 == null || salt1.Length == 0) salt1 = QRNG(SaltSize);
            if (salt2 == null || salt2.Length == 0) salt2 = QRNG(SaltSize);

            // A fresh IV per message. The old code reused one IV for the lifetime of
            // the instance, which for the stream-cipher plugins means keystream reuse.
            byte[] iv = QRNG(this.ivSize);
            this.IV = iv;

            KdfCost cost = KdfCost.Current();
            int[] ks = DeriveDigits(password1, password2, salt1, salt2, iv, cost, toEncrypt.Length);

            char[] outChars = new char[toEncrypt.Length];
            for (int i = 0; i < toEncrypt.Length; i++)
            {
                int p = toEncrypt[i] - AlphabetMin;
                outChars[i] = (char)(AlphabetMin + (p + ks[i]) % AlphabetSize);
            }

            rotations = ks.Length == 0 ? new int[1] : ks;

            return new CCryptData
            {
                CryptedData = new string(outChars),
                Key = "",              // no key material travels with the ciphertext, by design
                KdfParams = cost.ToString(),
                Salt = Convert.ToBase64String(salt1),
                Salt1 = Convert.ToBase64String(salt2),
                IV = iv
            };
        }

        /// <summary>
        /// Decrypts a <see cref="CCryptData"/>. Never throws on a wrong password: it
        /// returns a plausible printable string of the correct length, which is the
        /// whole point of the construction.
        /// </summary>
        public string decryptCCD(CCryptData cryptData, string password1, string password2)
        {
            if (cryptData == null) throw new ArgumentNullException("cryptData");

            string c = cryptData.CryptedData ?? "";
            byte[] salt1 = Convert.FromBase64String(cryptData.Salt);
            byte[] salt2 = Convert.FromBase64String(cryptData.Salt1);
            byte[] iv = cryptData.IV;

            // Cost parameters travel with the record, so changing the static defaults
            // never orphans data that was written under the old ones.
            KdfCost cost = KdfCost.Parse(cryptData.KdfParams);
            int[] ks = DeriveDigits(password1, password2, salt1, salt2, iv, cost, c.Length);

            char[] outChars = new char[c.Length];
            for (int i = 0; i < c.Length; i++)
            {
                int v = c[i] - AlphabetMin;
                if (v < 0 || v >= AlphabetSize)
                    throw new FormatException("Ciphertext contains a character outside the alphabet.");

                // + AlphabetSize keeps the result non-negative; C# % follows the sign
                // of the dividend, unlike the mathematical modulus we need here.
                outChars[i] = (char)(AlphabetMin + (v - ks[i] + AlphabetSize) % AlphabetSize);
            }

            rotationsDec = ks.Length == 0 ? new int[1] : ks;
            return new string(outChars);
        }

        /// <summary>Encrypts to a self-contained textual envelope.</summary>
        public string encryptString(string toEncrypt, string password1, string password2)
        {
            CCryptData d = encryptCCD(toEncrypt, password1, password2, null, null);

            StringBuilder sb = new StringBuilder(EnvelopeTag);
            sb.Append(EnvelopeSeparator).Append(d.Salt);
            sb.Append(EnvelopeSeparator).Append(d.Salt1);
            sb.Append(EnvelopeSeparator).Append(Convert.ToBase64String(d.IV));
            sb.Append(EnvelopeSeparator).Append(d.KdfParams);
            sb.Append(EnvelopeSeparator).Append(Convert.ToBase64String(Encoding.ASCII.GetBytes(d.CryptedData)));
            return sb.ToString();
        }

        /// <summary>Decrypts an envelope produced by <see cref="encryptString"/>.</summary>
        public string decryptString(string envelope, string password1, string password2)
        {
            if (envelope == null) throw new ArgumentNullException("envelope");

            string[] parts = envelope.Split(EnvelopeSeparator);
            if (parts.Length != 6 || parts[0] != EnvelopeTag)
            {
                if (parts.Length > 0 && parts[0] == "RW5")
                    throw new FormatException(
                        "This is an RW5 envelope, written by the PBKDF2 build. The Argon2id build " +
                        "cannot read it: the key derivation changed, so the key cannot be reproduced. " +
                        "Re-encrypt from plaintext with the current build.");

                throw new FormatException("Not a LibRincewind " + EnvelopeTag + " envelope.");
            }

            CCryptData d = new CCryptData
            {
                Salt = parts[1],
                Salt1 = parts[2],
                IV = Convert.FromBase64String(parts[3]),
                KdfParams = parts[4],
                CryptedData = Encoding.ASCII.GetString(Convert.FromBase64String(parts[5])),
                Key = ""
            };
            return decryptCCD(d, password1, password2);
        }

        // ------------------------------------------------------------- keystream --

        private static void RequireAlphabet(string s)
        {
            for (int i = 0; i < s.Length; i++)
            {
                if (s[i] < AlphabetMin || s[i] > AlphabetMax)
                    throw new ArgumentOutOfRangeException(
                        "toEncrypt",
                        string.Format(
                            "LibRincewind encrypts printable ASCII (U+0020..U+007E) only; " +
                            "found U+{0:X4} at index {1}. Encoding other input would add " +
                            "redundancy, and redundancy is exactly the key check this cipher " +
                            "exists to remove.",
                            (int)s[i], i));
            }
        }

        /// <summary>
        /// Produces <paramref name="count"/> uniform digits in [0,95) from the passwords.
        ///
        /// Key schedule, in two levels:
        ///   master  = Argon2id(pw1 | 0x1F | pw2, salt1 | salt2, m, t, p, 64 bytes)  [slow]
        ///   Kcore   = HMAC-SHA256(master[0..32],  iv | "core")                      [fast]
        ///   Kplug   = HMAC-SHA256(master[32..64], iv | "plug")                      [fast]
        ///   Kfinal  = HMAC-SHA256(Kcore, pluginKeystream | "LibRincewind-v6")
        ///
        /// Only the slow level depends on the salts, and only the fast level depends on the
        /// per-message IV. Message keys therefore stay unique (the IV is fresh every time)
        /// while an application that keeps one salt pair for a whole vault pays the KDF once
        /// rather than once per record — see <see cref="MasterKeyCacheSize"/>. Folding the IV
        /// into Argon2id instead would make every single record cost a full KDF pass for no
        /// extra security.
        ///
        /// The plugin is mixed in through an HMAC keyed by Kcore rather than XORed over the
        /// output. That keeps the plugin architecture meaningful — a plugin really does change
        /// the keystream — while making it impossible for a weak plugin to make the result
        /// weaker than plain AES-CTR under Kcore. RC4Plus in particular has a biased keystream
        /// and is O(256) per output byte; asking it for 32 bytes of key material instead of a
        /// full-length keystream costs nothing and inherits none of its bias.
        /// </summary>
        private int[] DeriveDigits(string password1, string password2,
                                   byte[] salt1, byte[] salt2, byte[] iv, KdfCost cost, int count)
        {
            byte[] master = GetMasterKey(password1, password2, salt1, salt2, cost);

            byte[] kCore, kPlug;
            try
            {
                kCore = SubKey(master, 0, iv, "core");
                kPlug = SubKey(master, 32, iv, "plug");
            }
            finally { Wipe(master); }   // GetMasterKey always hands back a private copy

            byte[] kFinal = MixPlugin(kCore, kPlug, iv, salt1, salt2);
            Wipe(kCore);
            Wipe(kPlug);

            try
            {
                return SampleDigits(kFinal, count);
            }
            finally
            {
                Wipe(kFinal);
            }
        }

        private byte[] MixPlugin(byte[] kCore, byte[] kPlug, byte[] iv, byte[] salt1, byte[] salt2)
        {
            byte[] contribution;
            if (this.plugin == null)
            {
                contribution = new byte[0];
            }
            else
            {
                // Both shipped plugins are stream ciphers, so encrypting zeros hands us
                // their raw keystream. Only encrypt() is ever called: never calling
                // decrypt() means a CBC-mode plugin cannot turn into a padding oracle.
                contribution = this.plugin.encrypt(
                    new byte[32], Convert.ToBase64String(kPlug), iv, salt1, salt2);
            }

            using (var mac = new HMACSHA256(kCore))
            {
                byte[] msg = Concat(contribution, Encoding.ASCII.GetBytes("LibRincewind-v6"));
                return mac.ComputeHash(msg);
            }
        }

        /// <summary>
        /// AES-256-CTR keystream, rejection-sampled down to uniform digits in [0,95).
        /// The key is unique per message (the IV is in the KDF salt), so the counter
        /// may start at zero.
        /// </summary>
        private static int[] SampleDigits(byte[] key, int count)
        {
            int[] digits = new int[count];
            if (count == 0) return digits;

            using (var aes = Aes.Create())
            {
                aes.Key = key;
                aes.Mode = CipherMode.ECB;
                aes.Padding = PaddingMode.None;

                using (ICryptoTransform ecb = aes.CreateEncryptor())
                {
                    byte[] counter = new byte[16];
                    byte[] block = new byte[16];
                    int produced = 0;

                    while (produced < count)
                    {
                        ecb.TransformBlock(counter, 0, 16, block, 0);
                        IncrementCounter(counter);

                        for (int i = 0; i < 16 && produced < count; i++)
                        {
                            int b = block[i];
                            if (b < RejectionBound)          // discard 190..255, keeps it unbiased
                                digits[produced++] = b % AlphabetSize;
                        }
                    }
                    Wipe(block);
                }
            }
            return digits;
        }

        private static void IncrementCounter(byte[] counter)
        {
            for (int i = counter.Length - 1; i >= 0; i--)
                if (++counter[i] != 0) break;
        }

        // ---------------------------------------------------------- Argon2id cost --

        /// <summary>
        /// The Argon2id cost of one record, serialised as "argon2id;m=65536;t=3;p=4".
        ///
        /// This travels with the ciphertext so that raising the defaults later does not
        /// orphan existing records. It is public metadata and creates no key-check oracle:
        /// the cost is identical for every candidate password, so knowing it tells an
        /// attacker only how long each guess will take, which they would learn from a
        /// stopwatch anyway.
        /// </summary>
        private struct KdfCost
        {
            public int MemoryKiB;
            public int Iterations;
            public int Parallelism;

            public static KdfCost Current()
            {
                KdfCost c;
                c.MemoryKiB = Argon2MemoryKiB;
                c.Iterations = Argon2Iterations;
                c.Parallelism = Argon2Parallelism;
                c.Validate("configuration");
                return c;
            }

            public override string ToString()
            {
                return "argon2id;m=" + MemoryKiB.ToString(CultureInfo.InvariantCulture) +
                       ";t=" + Iterations.ToString(CultureInfo.InvariantCulture) +
                       ";p=" + Parallelism.ToString(CultureInfo.InvariantCulture);
            }

            public static KdfCost Parse(string s)
            {
                if (string.IsNullOrEmpty(s))
                    throw new FormatException(
                        "This record carries no KdfParams. Records written by the RW5 (PBKDF2) " +
                        "build cannot be read by the Argon2id build.");

                string[] fields = s.Split(';');
                if (fields.Length != 4 || fields[0] != "argon2id")
                    throw new FormatException("Unsupported KdfParams '" + s + "'; expected argon2id;m=..;t=..;p=..");

                KdfCost c;
                c.MemoryKiB = Field(fields[1], "m=", s);
                c.Iterations = Field(fields[2], "t=", s);
                c.Parallelism = Field(fields[3], "p=", s);
                c.Validate("record");
                return c;
            }

            private static int Field(string field, string prefix, string whole)
            {
                if (!field.StartsWith(prefix, StringComparison.Ordinal))
                    throw new FormatException("Malformed KdfParams '" + whole + "': expected '" + prefix + "'.");

                int v;
                if (!int.TryParse(field.Substring(prefix.Length), NumberStyles.Integer,
                                  CultureInfo.InvariantCulture, out v))
                    throw new FormatException("Malformed KdfParams '" + whole + "': '" + field + "' is not a number.");
                return v;
            }

            /// <summary>
            /// Rejects costs that Argon2id cannot honour, and — for values that came from a
            /// record rather than from us — costs large enough to be a denial of service.
            /// A record is untrusted input; m=64GiB in a hostile envelope must be an error,
            /// not an allocation.
            /// </summary>
            private void Validate(string origin)
            {
                if (Parallelism < 1 || Parallelism > 64)
                    throw new FormatException("Argon2id parallelism " + Parallelism + " (from " + origin + ") is outside 1..64.");
                if (Iterations < 1 || Iterations > 64)
                    throw new FormatException("Argon2id iterations " + Iterations + " (from " + origin + ") is outside 1..64.");
                if (MemoryKiB < 8 * Parallelism)
                    throw new FormatException("Argon2id memory " + MemoryKiB + " KiB (from " + origin +
                                              ") is below the required 8 x parallelism = " + (8 * Parallelism) + " KiB.");
                if (MemoryKiB > Argon2MaxMemoryKiB)
                    throw new FormatException("Argon2id memory " + MemoryKiB + " KiB (from " + origin +
                                              ") exceeds Argon2MaxMemoryKiB = " + Argon2MaxMemoryKiB + " KiB.");
            }
        }

        // ------------------------------------------------------- master key cache --

        private static readonly object CacheLock = new object();
        private static readonly Dictionary<string, byte[]> MasterCache = new Dictionary<string, byte[]>();
        private static readonly List<string> CacheOrder = new List<string>();
        private static readonly byte[] CacheTag = RandomBytes(32);

        /// <summary>Drops every cached master key. Call this when locking a vault.</summary>
        public static void ClearKeyCache()
        {
            lock (CacheLock)
            {
                foreach (byte[] v in MasterCache.Values) Wipe(v);
                MasterCache.Clear();
                CacheOrder.Clear();
            }
        }

        private static byte[] GetMasterKey(string password1, string password2,
                                           byte[] salt1, byte[] salt2, KdfCost cost)
        {
            byte[] pw = ConcatPasswords(password1, password2);
            byte[] kdfSalt = Concat(salt1, salt2);

            if (kdfSalt.Length < 8)
                throw new ArgumentException("Argon2id needs a salt of at least 8 bytes.", "salt1");

            string cacheKey = null;
            if (MasterKeyCacheSize > 0)
            {
                // The cost parameters are part of the cache key: the same password under
                // different costs is a different master key.
                using (var mac = new HMACSHA256(CacheTag))
                    cacheKey = Convert.ToBase64String(
                        mac.ComputeHash(Concat(pw, kdfSalt, Encoding.ASCII.GetBytes(cost.ToString()))));

                lock (CacheLock)
                {
                    byte[] hit;
                    if (MasterCache.TryGetValue(cacheKey, out hit))
                    {
                        Wipe(pw);
                        return (byte[])hit.Clone();
                    }
                }
            }

            byte[] master;
            using (var argon2 = new Konscious.Security.Cryptography.Argon2id(pw))
            {
                argon2.Salt = kdfSalt;
                argon2.MemorySize = cost.MemoryKiB;
                argon2.Iterations = cost.Iterations;
                argon2.DegreeOfParallelism = cost.Parallelism;
                master = argon2.GetBytes(64);
            }
            Wipe(pw);

            if (cacheKey != null)
            {
                lock (CacheLock)
                {
                    if (!MasterCache.ContainsKey(cacheKey))
                    {
                        MasterCache[cacheKey] = (byte[])master.Clone();
                        CacheOrder.Add(cacheKey);
                        while (CacheOrder.Count > MasterKeyCacheSize)
                        {
                            string evict = CacheOrder[0];
                            CacheOrder.RemoveAt(0);
                            Wipe(MasterCache[evict]);
                            MasterCache.Remove(evict);
                        }
                    }
                }
            }
            return master;
        }

        /// <summary>Cheap per-message subkey: HMAC-SHA256(master[offset..offset+32], iv | label).</summary>
        private static byte[] SubKey(byte[] master, int offset, byte[] iv, string label)
        {
            byte[] half = new byte[32];
            Buffer.BlockCopy(master, offset, half, 0, 32);
            try
            {
                using (var mac = new HMACSHA256(half))
                    return mac.ComputeHash(Concat(iv, Encoding.ASCII.GetBytes(label)));
            }
            finally { Wipe(half); }
        }

        private static byte[] RandomBytes(int n)
        {
            byte[] b = new byte[n];
            using (var g = RandomNumberGenerator.Create()) g.GetBytes(b);
            return b;
        }

        private static byte[] ConcatPasswords(string p1, string p2)
        {
            // 0x1F (unit separator) cannot occur in UTF-8 text data, so ("ab","c") and
            // ("a","bc") derive different keys instead of colliding.
            byte[] a = Encoding.UTF8.GetBytes(p1 ?? "");
            byte[] b = Encoding.UTF8.GetBytes(p2 ?? "");
            byte[] r = new byte[a.Length + 1 + b.Length];
            Buffer.BlockCopy(a, 0, r, 0, a.Length);
            r[a.Length] = 0x1F;
            Buffer.BlockCopy(b, 0, r, a.Length + 1, b.Length);
            return r;
        }

        private static byte[] Concat(params byte[][] parts)
        {
            int n = 0;
            foreach (byte[] p in parts) n += (p == null ? 0 : p.Length);

            byte[] r = new byte[n];
            int o = 0;
            foreach (byte[] p in parts)
            {
                if (p == null) continue;
                Buffer.BlockCopy(p, 0, r, o, p.Length);
                o += p.Length;
            }
            return r;
        }

        private static void Wipe(byte[] b)
        {
            if (b != null) Array.Clear(b, 0, b.Length);
        }

        // --------------------------------------------------------------- entropy --

        /// <summary>
        /// Cryptographically secure random bytes, uniform over [min, max]
        /// (max = -1 means 255). Delegates to <see cref="Rng"/> when one is loaded.
        /// </summary>
        public static byte[] QRNG(int bytes, int min = 0, int max = -1, object[] parameters = null)
        {
            if (bytes < 0) throw new ArgumentOutOfRangeException("bytes");
            if (max < 0) max = 255;
            if (min < 0 || max > 255 || min > max)
                throw new ArgumentOutOfRangeException("min", "Require 0 <= min <= max <= 255.");

            IRng external = Rng;
            if (external != null)
            {
                byte[] fromRng = external.genBytes(bytes, min, max, parameters);

                // Never silently fall back to another source: a plugin RNG that returns
                // short, null or out-of-range data would hand us predictable salts while
                // everything still appeared to work. Both RNG plugins shipped with this
                // library are currently capable of that (the QRNG-API one dereferences
                // `parameters` unconditionally, the serial one loops on `while (b != -1)`),
                // so this check is the difference between a loud failure and silent
                // weak entropy.
                if (fromRng == null || fromRng.Length != bytes)
                    throw new CryptographicException(
                        external.GetType().FullName + " returned " +
                        (fromRng == null ? "null" : fromRng.Length + " bytes") +
                        " instead of " + bytes + ".");

                for (int i = 0; i < fromRng.Length; i++)
                    if (fromRng[i] < min || fromRng[i] > max)
                        throw new CryptographicException(
                            external.GetType().FullName + " returned " + fromRng[i] +
                            " at index " + i + ", outside the requested range [" + min + "," + max + "].");

                return fromRng;
            }

            byte[] result = new byte[bytes];
            if (bytes == 0) return result;

            int range = max - min + 1;
            using (var csprng = RandomNumberGenerator.Create())
            {
                if (range == 256)
                {
                    csprng.GetBytes(result);
                    return result;
                }

                // Same rejection trick as the digit sampler: modulo alone would make
                // the low end of the range more likely than the high end.
                int bound = (256 / range) * range;
                byte[] buffer = new byte[Math.Min(4096, Math.Max(64, bytes * 2))];
                int filled = 0, pos = buffer.Length;

                while (filled < bytes)
                {
                    if (pos == buffer.Length)
                    {
                        csprng.GetBytes(buffer);
                        pos = 0;
                    }
                    int b = buffer[pos++];
                    if (b < bound)
                        result[filled++] = (byte)(min + (b % range));
                }
                Wipe(buffer);
            }
            return result;
        }
    }
}
