<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>LibRincewindPlugin_4.7.2</AssemblyName>
    <RootNamespace>LibRincewind_4._7._2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CCryptData.cs" />
    <Compile Include="IPlugin.cs" />
    <Compile Include="AssemblyInfo.cs" />
  </ItemGroup>

</Project>
